#!/bin/sh

# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
  set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi

### BEGIN INIT INFO
# Provides:          desk-server
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Desk server
# Description:       Desk server
### END INIT INFO

DESC="desk server"
NAME=desk-server
DAEMON=/home/pi/go/src/github.com/visini/desk/desk-server
PIDFILE=/var/run/desk-server.pid
SCRIPTNAME=/etc/init.d/"$NAME"

test -f $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
start)  log_daemon_msg "Starting desk utility" "desk"
        start-stop-daemon --start -b -C --oknodo --exec $DAEMON --pidfile $PIDFILE --make-pidfile -- $EXTRA_OPTS
        log_end_msg $?
        ;;
stop)   log_daemon_msg "Stopping desk utility" "desk"
        start-stop-daemon --stop --oknodo --pidfile $PIDFILE --name "bridge"
        log_end_msg $?
        rm -f $PIDFILE
        ;;
restart) log_daemon_msg "Restarting desk utility" "desk"
        $0 stop
        $0 start
        ;;
status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
        ;;
*)      log_action_msg "Usage: /etc/init.d/desk {start|stop|status|restart}"
        exit 2
        ;;
esac
exit 0
